/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    portfolioProjects: PortfolioProject;
    careerRoles: CareerRole;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    portfolioProjects: PortfolioProjectsSelect<false> | PortfolioProjectsSelect<true>;
    careerRoles: CareerRolesSelect<false> | CareerRolesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    siteSettings: SiteSetting;
    homeContent: HomeContent;
    aboutContent: AboutContent;
    servicesContent: ServicesContent;
    contactContent: ContactContent;
    careersContent: CareersContent;
    legalPrivacy: LegalPrivacy;
    legalTerms: LegalTerm;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    homeContent: HomeContentSelect<false> | HomeContentSelect<true>;
    aboutContent: AboutContentSelect<false> | AboutContentSelect<true>;
    servicesContent: ServicesContentSelect<false> | ServicesContentSelect<true>;
    contactContent: ContactContentSelect<false> | ContactContentSelect<true>;
    careersContent: CareersContentSelect<false> | CareersContentSelect<true>;
    legalPrivacy: LegalPrivacySelect<false> | LegalPrivacySelect<true>;
    legalTerms: LegalTermsSelect<false> | LegalTermsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Admin = everything. Editor = content only.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers + SEO.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolioProjects".
 */
export interface PortfolioProject {
  id: number;
  name: string;
  client: string;
  market: string;
  discipline: string;
  /**
   * The one-line result.
   */
  resultLine: string;
  /**
   * Lower shows first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careerRoles".
 */
export interface CareerRole {
  id: number;
  title: string;
  /**
   * Full-time, Contract…
   */
  type: string;
  location: string;
  description: string;
  /**
   * Where "apply" links — a route or mailto:.
   */
  applyTarget?: string | null;
  /**
   * Lower shows first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'portfolioProjects';
        value: number | PortfolioProject;
      } | null)
    | ({
        relationTo: 'careerRoles';
        value: number | CareerRole;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolioProjects_select".
 */
export interface PortfolioProjectsSelect<T extends boolean = true> {
  name?: T;
  client?: T;
  market?: T;
  discipline?: T;
  resultLine?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careerRoles_select".
 */
export interface CareerRolesSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  location?: T;
  description?: T;
  applyTarget?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  shortName: string;
  /**
   * e.g. "Creative Rebellion is not chaos"
   */
  ideaTagline?: string | null;
  email: string;
  phone?: string | null;
  socials?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  letsChatLabel?: string | null;
  letsChatTarget?:
    | ('/' | '/about' | '/services' | '/portfolio' | '/careers' | '/contact' | '/privacy' | '/terms')
    | null;
  /**
   * Overlay menu, in order. Numbers (01, 02…) are added automatically.
   */
  menuItems?:
    | {
        label: string;
        route: '/' | '/about' | '/services' | '/portfolio' | '/careers' | '/contact' | '/privacy' | '/terms';
        id?: string | null;
      }[]
    | null;
  /**
   * Year is added automatically, e.g. "© 2026 {this text}".
   */
  footerCredit?: string | null;
  /**
   * Use %s for the page title, e.g. "%s — RMZ".
   */
  seoTitleTemplate?: string | null;
  seoDefaultTitle?: string | null;
  seoDefaultDescription?: string | null;
  seoDefaultOgImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homeContent".
 */
export interface HomeContent {
  id: number;
  showIntroLoader?: boolean | null;
  heroKicker?: string | null;
  /**
   * Each row is one styled fragment of the line, in order. Space is added between runs unless 'No space before' is set.
   */
  heroStatement?:
    | {
        text: string;
        style: 'normal' | 'italic' | 'bold' | 'bold-italic';
        tone: 'cream' | 'dim' | 'red';
        upper?: boolean | null;
        noSpaceBefore?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The small line under the hero statement.
   */
  heroSubline?: string | null;
  teaserCtaLabel?: string | null;
  /**
   * Optional overrides for this page's metadata. Blank = defaults.
   */
  seo?: {
    /**
     * Overrides the <title>.
     */
    title?: string | null;
    /**
     * Overrides the meta description / OG description.
     */
    description?: string | null;
    /**
     * Overrides the Open Graph image.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutContent".
 */
export interface AboutContent {
  id: number;
  /**
   * Each row is one styled fragment of the line, in order. Space is added between runs unless 'No space before' is set.
   */
  pageTitle?:
    | {
        text: string;
        style: 'normal' | 'italic' | 'bold' | 'bold-italic';
        tone: 'cream' | 'dim' | 'red';
        upper?: boolean | null;
        noSpaceBefore?: boolean | null;
        id?: string | null;
      }[]
    | null;
  lede?: string | null;
  /**
   * Idea / character / personality, in order.
   */
  sections?:
    | {
        kicker: string;
        title: string;
        body?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Each row is one styled fragment of the line, in order. Space is added between runs unless 'No space before' is set.
   */
  closingStatement?:
    | {
        text: string;
        style: 'normal' | 'italic' | 'bold' | 'bold-italic';
        tone: 'cream' | 'dim' | 'red';
        upper?: boolean | null;
        noSpaceBefore?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional overrides for this page's metadata. Blank = defaults.
   */
  seo?: {
    /**
     * Overrides the <title>.
     */
    title?: string | null;
    /**
     * Overrides the meta description / OG description.
     */
    description?: string | null;
    /**
     * Overrides the Open Graph image.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicesContent".
 */
export interface ServicesContent {
  id: number;
  /**
   * Each row is one styled fragment of the line, in order. Space is added between runs unless 'No space before' is set.
   */
  pageTitle?:
    | {
        text: string;
        style: 'normal' | 'italic' | 'bold' | 'bold-italic';
        tone: 'cream' | 'dim' | 'red';
        upper?: boolean | null;
        noSpaceBefore?: boolean | null;
        id?: string | null;
      }[]
    | null;
  lede?: string | null;
  /**
   * Ordered. The number (01, 02…) follows this order.
   */
  services?:
    | {
        title: string;
        blurb: string;
        items?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        featuredOnHome?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional overrides for this page's metadata. Blank = defaults.
   */
  seo?: {
    /**
     * Overrides the <title>.
     */
    title?: string | null;
    /**
     * Overrides the meta description / OG description.
     */
    description?: string | null;
    /**
     * Overrides the Open Graph image.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactContent".
 */
export interface ContactContent {
  id: number;
  /**
   * Each row is one styled fragment of the line, in order. Space is added between runs unless 'No space before' is set.
   */
  heroStory?:
    | {
        text: string;
        style: 'normal' | 'italic' | 'bold' | 'bold-italic';
        tone: 'cream' | 'dim' | 'red';
        upper?: boolean | null;
        noSpaceBefore?: boolean | null;
        id?: string | null;
      }[]
    | null;
  lede?: string | null;
  whereWeWorkLabel?: string | null;
  /**
   * The four markets, in order. Highlight = rendered in red.
   */
  markets?:
    | {
        label: string;
        isHighlighted?: boolean | null;
        categories?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        /**
         * "We solved the problems of…"
         */
        blurb?: string | null;
        /**
         * Email or phone for this market.
         */
        contactLine?: string | null;
        id?: string | null;
      }[]
    | null;
  form?: {
    /**
     * Where the form sends. Blank = the site email.
     */
    recipientEmail?: string | null;
    submitLabel?: string | null;
    successHeading?: string | null;
    successBody?: string | null;
    /**
     * Shown above the form when validation fails.
     */
    errorSummary?: string | null;
    fieldErrors?: {
      nameRequired?: string | null;
      emailRequired?: string | null;
      emailInvalid?: string | null;
      messageRequired?: string | null;
    };
  };
  /**
   * Optional overrides for this page's metadata. Blank = defaults.
   */
  seo?: {
    /**
     * Overrides the <title>.
     */
    title?: string | null;
    /**
     * Overrides the meta description / OG description.
     */
    description?: string | null;
    /**
     * Overrides the Open Graph image.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careersContent".
 */
export interface CareersContent {
  id: number;
  /**
   * Each row is one styled fragment of the line, in order. Space is added between runs unless 'No space before' is set.
   */
  pageTitle?:
    | {
        text: string;
        style: 'normal' | 'italic' | 'bold' | 'bold-italic';
        tone: 'cream' | 'dim' | 'red';
        upper?: boolean | null;
        noSpaceBefore?: boolean | null;
        id?: string | null;
      }[]
    | null;
  lede?: string | null;
  openApplicationHeading?: string | null;
  ctaLabel?: string | null;
  /**
   * Route or mailto:, e.g. "mailto:hello@…".
   */
  ctaTarget?: string | null;
  /**
   * Optional overrides for this page's metadata. Blank = defaults.
   */
  seo?: {
    /**
     * Overrides the <title>.
     */
    title?: string | null;
    /**
     * Overrides the meta description / OG description.
     */
    description?: string | null;
    /**
     * Overrides the Open Graph image.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legalPrivacy".
 */
export interface LegalPrivacy {
  id: number;
  title: string;
  /**
   * e.g. "2026"
   */
  lastUpdated?: string | null;
  showTemplateNotice?: boolean | null;
  intro?: string | null;
  /**
   * Use Heading 2 for each numbered section; paragraphs for the prose.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional overrides for this page's metadata. Blank = defaults.
   */
  seo?: {
    /**
     * Overrides the <title>.
     */
    title?: string | null;
    /**
     * Overrides the meta description / OG description.
     */
    description?: string | null;
    /**
     * Overrides the Open Graph image.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legalTerms".
 */
export interface LegalTerm {
  id: number;
  title: string;
  /**
   * e.g. "2026"
   */
  lastUpdated?: string | null;
  showTemplateNotice?: boolean | null;
  intro?: string | null;
  /**
   * Use Heading 2 for each numbered section; paragraphs for the prose.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional overrides for this page's metadata. Blank = defaults.
   */
  seo?: {
    /**
     * Overrides the <title>.
     */
    title?: string | null;
    /**
     * Overrides the meta description / OG description.
     */
    description?: string | null;
    /**
     * Overrides the Open Graph image.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  shortName?: T;
  ideaTagline?: T;
  email?: T;
  phone?: T;
  socials?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  letsChatLabel?: T;
  letsChatTarget?: T;
  menuItems?:
    | T
    | {
        label?: T;
        route?: T;
        id?: T;
      };
  footerCredit?: T;
  seoTitleTemplate?: T;
  seoDefaultTitle?: T;
  seoDefaultDescription?: T;
  seoDefaultOgImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homeContent_select".
 */
export interface HomeContentSelect<T extends boolean = true> {
  showIntroLoader?: T;
  heroKicker?: T;
  heroStatement?:
    | T
    | {
        text?: T;
        style?: T;
        tone?: T;
        upper?: T;
        noSpaceBefore?: T;
        id?: T;
      };
  heroSubline?: T;
  teaserCtaLabel?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutContent_select".
 */
export interface AboutContentSelect<T extends boolean = true> {
  pageTitle?:
    | T
    | {
        text?: T;
        style?: T;
        tone?: T;
        upper?: T;
        noSpaceBefore?: T;
        id?: T;
      };
  lede?: T;
  sections?:
    | T
    | {
        kicker?: T;
        title?: T;
        body?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  closingStatement?:
    | T
    | {
        text?: T;
        style?: T;
        tone?: T;
        upper?: T;
        noSpaceBefore?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicesContent_select".
 */
export interface ServicesContentSelect<T extends boolean = true> {
  pageTitle?:
    | T
    | {
        text?: T;
        style?: T;
        tone?: T;
        upper?: T;
        noSpaceBefore?: T;
        id?: T;
      };
  lede?: T;
  services?:
    | T
    | {
        title?: T;
        blurb?: T;
        items?:
          | T
          | {
              label?: T;
              id?: T;
            };
        featuredOnHome?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactContent_select".
 */
export interface ContactContentSelect<T extends boolean = true> {
  heroStory?:
    | T
    | {
        text?: T;
        style?: T;
        tone?: T;
        upper?: T;
        noSpaceBefore?: T;
        id?: T;
      };
  lede?: T;
  whereWeWorkLabel?: T;
  markets?:
    | T
    | {
        label?: T;
        isHighlighted?: T;
        categories?:
          | T
          | {
              label?: T;
              id?: T;
            };
        blurb?: T;
        contactLine?: T;
        id?: T;
      };
  form?:
    | T
    | {
        recipientEmail?: T;
        submitLabel?: T;
        successHeading?: T;
        successBody?: T;
        errorSummary?: T;
        fieldErrors?:
          | T
          | {
              nameRequired?: T;
              emailRequired?: T;
              emailInvalid?: T;
              messageRequired?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careersContent_select".
 */
export interface CareersContentSelect<T extends boolean = true> {
  pageTitle?:
    | T
    | {
        text?: T;
        style?: T;
        tone?: T;
        upper?: T;
        noSpaceBefore?: T;
        id?: T;
      };
  lede?: T;
  openApplicationHeading?: T;
  ctaLabel?: T;
  ctaTarget?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legalPrivacy_select".
 */
export interface LegalPrivacySelect<T extends boolean = true> {
  title?: T;
  lastUpdated?: T;
  showTemplateNotice?: T;
  intro?: T;
  body?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legalTerms_select".
 */
export interface LegalTermsSelect<T extends boolean = true> {
  title?: T;
  lastUpdated?: T;
  showTemplateNotice?: T;
  intro?: T;
  body?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}